### PR TITLE
Task-118: Decoupled getQuestionID using DAOs

### PR DESCRIPTION
**Pull request by PaHorton**
Proposed change to getQuestionID

### CODE REVIEW

**Comment by dlahtine** [comment]
This change looks good, but I won't be able to test it for a while.

**Review by HalcyonAura — COMMENTED** [review]
Much cleaner code. Looks better

**Review by rubyqzhao — APPROVED** [review]
You were right, this is a much better way to do it.

**Review by dlahtine — APPROVED** [review]
Looks Great!

**Pull request merged**
